import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

function formatMoney(value, currency = "USD") {
  const normalizedCurrency = String(currency || "USD").toUpperCase();
  const amount = new Intl.NumberFormat("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Number(value || 0));
  return `${normalizedCurrency} ${amount}`;
}

function safePdfText(value) {
  return String(value ?? "")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "?");
}

function formatDate(value) {
  if (!value) {
    return "Not captured";
  }

  const raw = String(value);
  const parsed = new Date(raw.includes("T") ? raw : `${raw}T12:00:00.000Z`);
  if (Number.isNaN(parsed.getTime())) {
    return raw;
  }

  return parsed.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function sanitizeFilenamePart(value) {
  return String(value || "")
    .trim()
    .replace(/[^a-zA-Z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function formatPaymentType(value) {
  return String(value || "payment")
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function buildEmployeePayslipPdfFilename({ employee, payslip }) {
  const employeeCode = sanitizeFilenamePart(employee?.employee_code ?? employee?.employeeCode);
  const period = sanitizeFilenamePart(payslip?.pay_period_label ?? payslip?.payPeriodLabel);
  return `setu-payslip-${employeeCode || "employee"}-${period || "period"}.pdf`;
}

export async function generateEmployeePayslipPdf({ employee, payslip, payments = [] }) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]);
  const regularFont = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

  const margin = 54;
  const pageWidth = page.getWidth();
  const ink = rgb(0.12, 0.13, 0.17);
  const subtle = rgb(0.42, 0.45, 0.52);
  const accent = rgb(0.71, 0.43, 0.08);
  const line = rgb(0.88, 0.89, 0.92);
  const currency = payslip?.currency || employee?.currency || payments[0]?.currency || "USD";

  function drawText(value, options) {
    page.drawText(safePdfText(value), options);
  }

  drawText("Setu Finance", {
    x: margin,
    y: 744,
    size: 12,
    font: boldFont,
    color: accent,
  });
  drawText("Employee Payslip", {
    x: margin,
    y: 708,
    size: 26,
    font: boldFont,
    color: ink,
  });
  drawText("Generated from recorded employee payment transactions in Setu Finance.", {
    x: margin,
    y: 688,
    size: 11,
    font: regularFont,
    color: subtle,
  });
  page.drawLine({
    start: { x: margin, y: 670 },
    end: { x: pageWidth - margin, y: 670 },
    thickness: 1,
    color: line,
  });

  const rows = [
    ["Employee", [employee?.first_name, employee?.middle_name, employee?.last_name].filter(Boolean).join(" ")],
    ["Employee ID", employee?.employee_code ?? "Not captured"],
    ["Department / title", [employee?.department, employee?.title].filter(Boolean).join(" / ")],
    ["Region", employee?.region ?? "Not captured"],
    ["Pay period", payslip?.pay_period_label ?? "Not captured"],
    ["Period range", `${formatDate(payslip?.period_start)} - ${formatDate(payslip?.period_end)}`],
    ["Gross amount", formatMoney(payslip?.gross_amount, currency)],
    ["Generated by", payslip?.generated_by_username ?? "Setu Finance"],
    ["Generated on", formatDate(payslip?.generated_at ?? new Date().toISOString())],
  ];

  let cursorY = 638;
  for (const [label, value] of rows) {
    drawText(label, {
      x: margin,
      y: cursorY,
      size: 10,
      font: boldFont,
      color: subtle,
    });
    drawText(String(value || "Not captured"), {
      x: 220,
      y: cursorY,
      size: 11,
      font: regularFont,
      color: ink,
    });
    cursorY -= 26;
  }

  cursorY -= 4;
  page.drawLine({
    start: { x: margin, y: cursorY },
    end: { x: pageWidth - margin, y: cursorY },
    thickness: 1,
    color: line,
  });
  cursorY -= 30;

  drawText("Payment details", {
    x: margin,
    y: cursorY,
    size: 15,
    font: boldFont,
    color: ink,
  });
  cursorY -= 26;

  if (payments.length) {
    for (const payment of payments) {
      drawText(formatPaymentType(payment.payment_type), {
        x: margin,
        y: cursorY,
        size: 10,
        font: boldFont,
        color: ink,
      });
      drawText(formatDate(payment.payment_date), {
        x: 220,
        y: cursorY,
        size: 10,
        font: regularFont,
        color: subtle,
      });
      drawText(formatMoney(payment.amount, payment.currency || currency), {
        x: 410,
        y: cursorY,
        size: 10,
        font: regularFont,
        color: ink,
      });
      cursorY -= 18;
      if (payment.memo || payment.reference) {
        drawText(String(payment.memo || payment.reference).slice(0, 92), {
          x: margin,
          y: cursorY,
          size: 9,
          font: regularFont,
          color: subtle,
        });
        cursorY -= 20;
      } else {
        cursorY -= 8;
      }
    }
  } else {
    drawText("No payment transactions were linked to this payslip period.", {
      x: margin,
      y: cursorY,
      size: 10,
      font: regularFont,
      color: subtle,
    });
    cursorY -= 24;
  }

  page.drawLine({
    start: { x: margin, y: cursorY },
    end: { x: pageWidth - margin, y: cursorY },
    thickness: 1,
    color: line,
  });
  drawText("This payslip is generated for sharing with the employee and reflects records saved in Setu Finance.", {
    x: margin,
    y: cursorY - 26,
    size: 9,
    font: regularFont,
    color: subtle,
  });

  return Buffer.from(await pdf.save());
}
